apiVersion: v1
kind: Secret
metadata:
  name: dkusecret-doctor-preprocessing-qndrvix
type: Opaque
data:
  apiticket: aHRSa3lIUVJ5VFNNc3hVSVQ1VFdONTlhMVgwNWtpRkJCWk96dVkweW15bFUzeVl2QnRENUVhVlBoNDFScUh1bw== # base64