apiVersion: v1
kind: Secret
metadata:
  name: dkusecret-doctor-preprocessing-rajpxgs
type: Opaque
data:
  apiticket: Nm9ySXlpVWswSDhEenZxaWk1MmJwYlhJSkdmMU4zcEpXWmZiY0hraWRPTFZYcFI1ZVdHRHJHR2F1UWxuREU4cA== # base64