apiVersion: v1
kind: Secret
metadata:
  name: dkusecret-doctor-interactive-scoring-fd5casa
type: Opaque
data:
  apiticket: R0VCSWVpdFpOWktFTkpEVmlMS0V5SVgxVkIzUXpVNGR1ZlZRSE55eXdGdU1xb2ExbGNzcVFrUE1mRHdEZnk0VQ== # base64